# Generated by Django 4.2.7 on 2023-11-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofiles', '0002_userprofile_email_userprofile_name_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
